steps:
  - label: "Nvidia GPUs -- CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
    agents:
      queue: "cuda"
    command: |
      julia --color=yes --project -e '
        using Pkg
        Pkg.add("CUDA")
        Pkg.add("LinearOperators")
        Pkg.add("KernelAbstractions")
        Pkg.instantiate()
        using CUDA
        # CUDA.set_runtime_version!(v"12.9")'

      julia --color=yes --project -e '
        include("test/gpu/nvidia.jl")'
    timeout_in_minutes: 30

  - label: "AMD GPUs -- AMDGPU.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
    agents:
      queue: "rocm"
      rocmgpu: "*"
    env:
      JULIA_NUM_THREADS: 4
      JULIA_AMDGPU_CORE_MUST_LOAD: "1"
      JULIA_AMDGPU_HIP_MUST_LOAD: "1"
      JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
    command: |
      julia --color=yes --project -e '
        using Pkg
        Pkg.add("AMDGPU")
        Pkg.add("KernelAbstractions")
        Pkg.instantiate()
        include("test/gpu/amd.jl")'
    timeout_in_minutes: 30

  - label: "Intel GPUs -- oneAPI.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
    agents:
      queue: "oneapi"
    command: |
      julia --color=yes --project -e '
        using Pkg
        # Pkg.add(url="https://github.com/JuliaGPU/oneAPI.jl", rev="master")
        Pkg.add("oneAPI")
        Pkg.add("KernelAbstractions")
        Pkg.instantiate()
        include("test/gpu/intel.jl")'
    timeout_in_minutes: 30
