steps:
  - label: "Example 1 -- JOSS"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
    agents:
      os: "linux"
      arch: "x86_64"
    command: |
      julia --color=yes --project=./paper/example1 -e '
      using Pkg
      Pkg.instantiate()
      include("paper/example1/example1.jl")'
    timeout_in_minutes: 30

  - label: "Example 2 -- JOSS"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project=./paper/example2 -e '
      using Pkg
      Pkg.instantiate()
      include("paper/example2/example2.jl")'
    timeout_in_minutes: 30
